### ISSUE TITLE
pipdate doesn't show update instructions on Mac platforms

### ISSUE THREAD

**Issue by jtrivedi** [nschloe/pypi_update_checker#23]
I'd love to use pipdate, but unfortunately, pipdate seems to only print the `run pip install -U package_name` message if the target is `linux` or `linux2`.

For macOS, where `sys.platform` is `darwin`, it doesn't show update instructions, nor does the API provide any way to do so manually.

Is this something that you're interested in adding? Thanks!

**Comment by nschloe** [comment]
pipdate now checks if pip/pip3 is available and prints the message then.

**Comment by jtrivedi** [comment]
Great, thank you so much!
