### ISSUE TITLE
Command no found

### ISSUE THREAD

**Issue by shinokada** [nschloe/pypi_update_checker#34]
Hi,

After the installation, when I run `pipdate`, I get the following error.

```
zsh: command not found: pipdate
```

Do I need to add $PATH?

**Comment by nschloe** [comment]
Ah, it's `pipdate3`, I messed up something in the last update.

**Comment by nschloe** [comment]
Fixed in 0.4.1.

**Comment by shinokada** [comment]
Please update the Readme file. 
Thanks.

**Comment by nschloe** [comment]
Why?

**Comment by shinokada** [comment]
I thought we need to run `pindate3`.

**Comment by nschloe** [comment]
It's fixed now.
