### ISSUE TITLE
Only update pip packages for the version of Python pipdate was installed to.

### ISSUE THREAD

**Issue by Fooughhy** [nschloe/pypi_update_checker#37]
Hi!

I'm using linux-mint and am running 4 different versions of python on it. To not mess with the default packages I use the command `Python3.7 -m pip install pipdate` to install pipdate only for Python3.7 (and this is performed correctly as I see `pipdate` when I run `python3.7 -m pip freeze`.

The issue is that I can not run `pipdate` using this approach, I have to run it as just `pipdate` in the terminal. It would be really helpful if I could run it in each instance of pip to update them seperately, such as `python3.8 -m pipdate` and `python3.6 -m pipdate`.

**Comment by nschloe** [comment]
Thanks for the report; should work now.
